import os
from typing import Union, Optional
import numpy as np
from pathlib import Path
from app.models.grade import ColorGradeParams, GradePlan, CreativeLookParams, OutputTransformParams
from app.models.analysis import CreativeSpecification
from app.media.color import apply_color_grade_to_frame

def generate_3d_cube_lut(
    plan_or_params: Union[GradePlan, ColorGradeParams],
    output_path: str,
    size: int = 33,
    title: str = "Autonomous_Colorist_Grade",
    is_log: bool = False
) -> str:
    lut_dir = os.path.dirname(output_path)
    if lut_dir:
        os.makedirs(lut_dir, exist_ok=True)
        
    # Generate 3D RGB floating-point lattice in [0.0, 1.0] with full 32-bit precision
    r = np.linspace(0.0, 1.0, size, dtype=np.float32)
    g = np.linspace(0.0, 1.0, size, dtype=np.float32)
    b = np.linspace(0.0, 1.0, size, dtype=np.float32)
    
    # Shape: (size * size, size, 3) with BGR ordering: [b, g, r]
    lattice = np.zeros((size * size, size, 3), dtype=np.float32)
    for b_idx in range(size):
        for g_idx in range(size):
            row_idx = b_idx * size + g_idx
            for r_idx in range(size):
                lattice[row_idx, r_idx] = [b[b_idx], g[g_idx], r[r_idx]]
                
    # Apply staged color transformation with floating-point precision
    graded_lattice = apply_color_grade_to_frame(lattice, plan_or_params, is_log=is_log)
    
    # Ensure float32 representation
    if graded_lattice.dtype == np.uint8:
        graded_lattice = graded_lattice.astype(np.float32) / 255.0
        
    # Format and write standard Adobe / DaVinci Resolve .cube file
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(f"# Generated by Autonomous Multimodal Colorist Assistant\n")
        f.write(f"TITLE \"{title}\"\n")
        f.write(f"LUT_3D_SIZE {size}\n")
        f.write("DOMAIN_MIN 0.0 0.0 0.0\n")
        f.write("DOMAIN_MAX 1.0 1.0 1.0\n\n")
        
        for b_idx in range(size):
            for g_idx in range(size):
                row_idx = b_idx * size + g_idx
                for r_idx in range(size):
                    b_out, g_out, r_out = graded_lattice[row_idx, r_idx]
                    f.write(f"{float(r_out):.6f} {float(g_out):.6f} {float(b_out):.6f}\n")
                    
    return output_path

def generate_shared_creative_look_lut(
    creative_spec: CreativeSpecification,
    output_path: str,
    size: int = 33
) -> str:
    from app.tools.calculate_grade import parse_highlight_bias_rgb, parse_shadow_bias_rgb, parse_black_level_lift
    
    plan = GradePlan(shot_id="shared_creative_look", is_same_scene=False)
    h_rgb = parse_highlight_bias_rgb(creative_spec.highlight_bias)
    s_rgb = parse_shadow_bias_rgb(creative_spec.shadow_bias)
    toe_lift = parse_black_level_lift(creative_spec.black_level_treatment, creative_spec.black_mist_diffusion_strength)
    
    plan.creative_look = CreativeLookParams(
        look_title=creative_spec.look_title,
        contrast=creative_spec.contrast_intent,
        pivot=0.45,
        saturation=creative_spec.saturation_intent,
        shadow_rgb_offset=s_rgb,
        highlight_rgb_offset=h_rgb,
        black_toe_lift=toe_lift,
        black_mist_strength=creative_spec.black_mist_diffusion_strength
    )
    plan.technical_balance.temperature = creative_spec.temperature_shift
    plan.technical_balance.tint = creative_spec.tint_shift
    
    return generate_3d_cube_lut(
        plan_or_params=plan,
        output_path=output_path,
        size=size,
        title=f"Shared_Look_{creative_spec.look_title.replace(' ', '_')}",
        is_log=False
    )