import os
import numpy as np
from pathlib import Path
from app.models.grade import ColorGradeParams
from app.media.color import apply_color_grade_to_frame

def generate_3d_cube_lut(
    params: ColorGradeParams,
    output_path: str,
    size: int = 33,
    title: str = "Autonomous_Colorist_Grade",
    is_log: bool = False
) -> str:
    lut_dir = os.path.dirname(output_path)
    if lut_dir:
        os.makedirs(lut_dir, exist_ok=True)
        
    # Generate 3D RGB lattice points
    lattice = np.zeros((size * size, size, 3), dtype=np.uint8)
    
    # Fill lattice
    for b_idx in range(size):
        for g_idx in range(size):
            row_idx = b_idx * size + g_idx
            for r_idx in range(size):
                r_val = int(round(r_idx * 255.0 / (size - 1)))
                g_val = int(round(g_idx * 255.0 / (size - 1)))
                b_val = int(round(b_idx * 255.0 / (size - 1)))
                lattice[row_idx, r_idx] = [b_val, g_val, r_val] # BGR
                
    # Apply color transformation + Log CST if needed
    graded_lattice = apply_color_grade_to_frame(lattice, params, is_log=is_log)
    
    # Format and write .cube file
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(f"# Generated by Autonomous Multimodal Colorist Assistant\n")
        f.write(f"TITLE \"{title}\"\n")
        f.write(f"LUT_3D_SIZE {size}\n")
        f.write("DOMAIN_MIN 0.0 0.0 0.0\n")
        f.write("DOMAIN_MAX 1.0 1.0 1.0\n\n")
        
        for b_idx in range(size):
            for g_idx in range(size):
                row_idx = b_idx * size + g_idx
                for r_idx in range(size):
                    b_out, g_out, r_out = graded_lattice[row_idx, r_idx]
                    r_norm = r_out / 255.0
                    g_norm = g_out / 255.0
                    b_norm = b_out / 255.0
                    f.write(f"{r_norm:.6f} {g_norm:.6f} {b_norm:.6f}\n")
                    
    return output_path